<script>
	import { fade } from 'svelte/transition';
	import '../../app.css';

	let arr = [];
	let fetched = false;
	let clicked = false;

	async function onbuttonclick() {
		clicked = true;
		let url = 'https://dvckapp.xyz/api';
		let data = await fetch(url);
		arr.push(await data.json());
		if (arr) {
			fetched = true;
			console.log(arr[0]);
		}
	}
	async function get() {
		const res = await fetch(arr[0]);
		return {
			body: res.body
		};
	}
</script>

<body transition:fade class="font-poppins bg-black w-screen h-screen justify-center">
	<div class="navbar sticky top-0 z-50">
		<div class="flex-1">
			<a href="/" class="btn btn-ghost normal-case text-xl">Home</a>
		</div>
	</div>
	<div class="flex h-[calc(100vh-64px)] place-items-center">
		<div class="m-auto">
			{#if fetched}
				<div class="grid gap-3">
					<h3 class="text-4xl text-center text-white">iPlay Timetable Starting {arr[0][0]}</h3>
					<img transition:fade src={arr[0][1]} alt="timetable" />
				</div>
			{:else if clicked}
				<div class="loadingio-spinner-eclipse-h5of8z52o7">
					<div class="ldio-oiy8vzir9dr">
						<div />
					</div>
				</div>
			{:else if clicked != true}
				<button class="btn" on:click={onbuttonclick}>get timetable</button>
			{/if}
			<div />
		</div>
	</div>
</body>

<style type="text/css">
	@keyframes ldio-oiy8vzir9dr {
		0% {
			transform: rotate(0deg);
		}
		50% {
			transform: rotate(180deg);
		}
		100% {
			transform: rotate(360deg);
		}
	}
	.ldio-oiy8vzir9dr div {
		position: absolute;
		animation: ldio-oiy8vzir9dr 1s linear infinite;
		width: 160px;
		height: 160px;
		top: 20px;
		left: 20px;
		border-radius: 50%;
		box-shadow: 0 4px 0 0 #ffffff;
		transform-origin: 80px 82px;
	}
	.loadingio-spinner-eclipse-h5of8z52o7 {
		width: 200px;
		height: 200px;
		display: inline-block;
		overflow: hidden;
		background: none;
	}
	.ldio-oiy8vzir9dr {
		width: 100%;
		height: 100%;
		position: relative;
		transform: translateZ(0) scale(1);
		backface-visibility: hidden;
		transform-origin: 0 0; /* see note above */
	}
	.ldio-oiy8vzir9dr div {
		box-sizing: content-box;
	}
	/* generated by https://loading.io/ */
</style>
